AWSTemplateFormatVersion: 2010-09-09
Description: Template to provision DynamoDB Zero ETL to Amazon OpenSearch with automatic embeddings
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Required Parameters
        Parameters:
          - OpenSearchUsername
          - OpenSearchPassword
          - OpenSearchIndexName
    ParameterLabels:
      OpenSearchUsername:
        default: OpenSearch domain username
      OpenSearchPassword:
        default: OpenSearch domain password
      OpenSearchIndexName:
        default: OpenSearch index name
      BedrockRegion:
        default: Amazon Bedrock region
      ImageStoreDynamodbTableName:
        default: DynamoDB table for image store
      ImageStoreDynamodbTableArn:
        default: ARN for DynamoDB table for image store

Parameters:
  OpenSearchUsername:
    AllowedPattern: "^[a-zA-Z0-9]+$"
    Default: cs52962026
    Description: opensearch username
    MaxLength: "25"
    MinLength: "5"
    Type: String
  OpenSearchPassword:
    AllowedPattern: '(?=^.{8,32}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))^.*'
    Description: opensearch password
    MaxLength: "32"
    MinLength: "8"
    NoEcho: "true"
    Type: String
    Default: Cs52962026!
  OpenSearchIndexName:
    Default: cs5296-index
    Type: String
    Description: opensearch index name
  BedrockRegion:
    Default: us-east-1
    Type: String
    Description: aws bedrock region
    AllowedValues:
      - us-east-1
  S3BucketCodeArtifact:
    Default: cs5296-s3-bucket-code-artifact
    Type: String
    Description: S3 bucket for Lambda code artifacts
  ImageStoreDynamodbTable:
    Default: image_store
    Type: String
    Description: DynamoDB table name for image store
  ImageStoreDynamodbTableArn:
    Default: arn:aws:dynamodb:us-east-1:123456789012:table/image_store
    Type: String
    Description: ARN for the DynamoDB table for image store
Resources:
  CommonApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: cs5296-common-api
      Description: API Gateway for common APIs
  # ImageStoreDynamodbTable:
  #   DeletionPolicy: Retain
  #   UpdateReplacePolicy: Retain
  #   Type: "AWS::DynamoDB::Table"
  #   Properties:
  #     TableName: image_store
  #     BillingMode: PAY_PER_REQUEST
  #     AttributeDefinitions:
  #       - AttributeName: "PK"
  #         AttributeType: "S"
  #       - AttributeName: "SK"
  #         AttributeType: "S"
  #     KeySchema:
  #       - AttributeName: "PK"
  #         KeyType: "HASH"
  #       - AttributeName: "SK"
  #         KeyType: "RANGE"
  # IAM Role for OpenSearch Service to access Amazon Bedrock
  OpenSearchBedrockRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cs5296-opensearch-bedrock-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: es.amazonaws.com
            Action: sts:AssumeRole
          - Effect: Allow
            Principal:
              Service: es.aws.internal
            Action: sts:AssumeRole
      Policies:
        - PolicyName: OpenSearchAccessAIModelPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: arn:aws:bedrock:*::foundation-model/*

  # IAM role for Amazon Lambda to access Amazon OpenSearch and Amazon S3
  LambdaOpenSearchRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cs5296-lambda-opensearch-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: OSMappingLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - iam:ListRoles
                  - iam:PassRole
                  - iam:GetRole
                  - iam:CreateRole
                  - iam:GetRolePolicy
                  - iam:CreatePolicy
                  - iam:AttachRolePolicy
                  - iam:PutRolePolicy
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:DeleteObject
                  - s3:DeleteBucket
                Resource: "*"
              - Effect: Allow
                Action:
                  - "*"
                Resource: "*"

  # IAM Role for the OpenSearch Ingestion pipeline
  IngestionPipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cs5296-ingestion-pipeline-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - osis-pipelines.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: PipelineRolePolicies
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - es:DescribeDomain
                Resource: "*"
              - Effect: Allow
                Action:
                  - es:ESHttp*
                Resource: "*"
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource:
                  - !Ref ImageStoreDynamodbTableArn
                  - !Join ["", [!Ref ImageStoreDynamodbTableArn, "/export/*"]]
                  - !Join ["", [!Ref ImageStoreDynamodbTableArn, "/stream/*"]]
              - Effect: Allow
                Action:
                  - osis:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:*
                Resource: !Join ["", [!GetAtt S3BucketMain.Arn, "/*"]]

  # S3 bucket for the Lambda function code and dependencies
  # S3BucketCodeArtifact:
  #   DeletionPolicy: Retain
  #   UpdateReplacePolicy: Retain
  #   Type: "AWS::S3::Bucket"
  #   Properties:
  #     BucketName: cs5296-s3-bucket-code-artifact

  # S3 bucket for the OpenSearch Ingestion pipeline
  S3BucketMain:
    DependsOn:
      - SQSImageProcessingQueue
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: cs5296-s3-bucket-main
      NotificationConfiguration:
        QueueConfigurations:
          - Event: "s3:ObjectCreated:*"
            Queue: !GetAtt SQSImageProcessingQueue.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: ".jpg"
      Tags:
        - Key: "StorageClass"
          Value: "Standard"

  # S3 bucket for Standard-IA storage class
  S3BucketStandardIA:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: cs5296-s3-bucket-standard-ia
      LifecycleConfiguration:
        Rules:
          - Id: StandardIARule
            Status: Enabled
            Transitions:
              - TransitionInDays: 31
                StorageClass: STANDARD_IA
      Tags:
        - Key: "StorageClass"
          Value: "StandardIA"

  # S3 bucket for Glacie Flexible Retrieval
  S3BucketGlacierFlexibleRetrieval:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: cs5296-s3-bucket-glacier-flexible-retrieval
      LifecycleConfiguration:
        Rules:
          - Id: GlacierFlexibleRetrievalRule
            Status: Enabled
            Transitions:
              - TransitionInDays: 0
                StorageClass: GLACIER
      Tags:
        - Key: "StorageClass"
          Value: "GlacierFlexibleRetrieval"

  # S3 bucket for Glacie Instant Retrieval
  S3BucketGlacierInstantRetrieval:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: cs5296-s3-bucket-glacier-instant-retrieval
      LifecycleConfiguration:
        Rules:
          - Id: GlacierFlexibleRetrievalRule
            Status: Enabled
            Transitions:
              - TransitionInDays: 0
                StorageClass: GLACIER_IR
      Tags:
        - Key: "StorageClass"
          Value: "GlacierInstantRetrieval"
  SQSImageProcessingQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: cs5296-image-processing-queue
      VisibilityTimeout: 1200
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 20

  SQSImageProcessingQueuePolicy:
    DependsOn:
      - SQSImageProcessingQueue
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: SQS:SendMessage
            Resource: "*"
            Condition:
              ArnLike:
                aws:SourceArn: "arn:aws:s3:::*"
      Queues:
        - !Ref SQSImageProcessingQueue
  # Lambda Layer for common dependencies
  CommonLambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: common-lambda-layer
      Description: Common Lambda Layer
      Content:
        S3Bucket: !Ref S3BucketCodeArtifact
        S3Key: common_lambda_layer.zip
      CompatibleRuntimes:
        - python3.12

  LambdaImageProcessingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cs5296-lambda-image-processing-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess

  ImageProcessingLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "main.lambda_handler"
      Role: !GetAtt LambdaImageProcessingRole.Arn
      Layers:
        - !Ref CommonLambdaLayer
      Code:
        S3Bucket: !Ref S3BucketCodeArtifact
        S3Key: image_processing_lambda.zip
      Runtime: python3.12
      Timeout: 900
      Environment:
        Variables:     
          S3_BUCKET_MAIN: !Ref S3BucketMain
          IMAGE_STORE_DYNAMODB_TABLE: !Ref ImageStoreDynamodbTable

  SQSQueueEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      EventSourceArn: !GetAtt SQSImageProcessingQueue.Arn
      FunctionName: !Ref ImageProcessingLambda
      Enabled: True

  LambdaQueryHandlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cs5296-lambda-query-handler-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess

  QueryHandlerLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "main.lambda_handler"
      Role: !GetAtt LambdaQueryHandlerRole.Arn
      Layers:
        - !Ref CommonLambdaLayer
      Code:
        S3Bucket: !Ref S3BucketCodeArtifact
        S3Key: query_handler.zip
      Runtime: python3.12
      Timeout: 900
      Environment:
        Variables:
          S3_BUCKET_MAIN: !Ref S3BucketMain
          IMAGE_STORE_DYNAMODB_TABLE: !Ref ImageStoreDynamodbTable

  LambdaS3TieringRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cs5296-lambda-s3-tiering-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - scheduler.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonEventBridgeFullAccess

  S3TieringHandlerLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "main.lambda_handler"
      Role: !GetAtt LambdaS3TieringRole.Arn
      Layers:
        - !Ref CommonLambdaLayer
      Code:
        S3Bucket: !Ref S3BucketCodeArtifact
        S3Key: s3_tiering_handler.zip
      Runtime: python3.12
      Timeout: 900
      Environment:
        Variables:
          S3_BUCKET_MAIN: !Ref S3BucketMain
          S3_STANDARD_IA_BUCKET: !Ref S3BucketStandardIA
          S3_GLACIER_FLEXIBLE_RETRIEVAL_BUCKET: !Ref S3BucketGlacierFlexibleRetrieval
          S3_GLACIER_INSTANT_RETRIEVAL_BUCKET: !Ref S3BucketGlacierInstantRetrieval

  S3TieringHandlerEventTriggerRule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: "Schedule to trigger S3 tiering Lambda function every hour"
      Name: s3-tiering-handler-event-trigger-rule
      FlexibleTimeWindow:
        Mode: FLEXIBLE
        MaximumWindowInMinutes: 15
      ScheduleExpression: rate(1 hour)
      State: ENABLED
      Target: 
        Arn: !GetAtt S3TieringHandlerLambda.Arn
        RoleArn: !GetAtt LambdaS3TieringRole.Arn

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref S3TieringHandlerLambda
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "S3TieringHandlerEventTriggerRule"
          - "Arn"

  # Amazon OpenSearch Ingestion Log Group
  IngestionPipelineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ["", ["/aws/vendedlogs/pipelinelogs", ddbaosingestionpipeline]]
      RetentionInDays: 7

  # Amazon OpenSearch Domain
  OpenSearchServiceDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: cs5296-opensearch-2026
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: "es:*"
            Resource: !Sub arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/*/*
      EngineVersion: "OpenSearch_3.1"
      ClusterConfig:
        InstanceType: "t3.small.search"
        InstanceCount: 1
      EBSOptions:
        EBSEnabled: True
        VolumeSize: 20
        VolumeType: "gp3"
      AdvancedSecurityOptions:
        AnonymousAuthEnabled: False
        Enabled: True
        InternalUserDatabaseEnabled: True
        MasterUserOptions:
          MasterUserName: !Sub ${OpenSearchUsername}
          MasterUserPassword: !Sub ${OpenSearchPassword}
      NodeToNodeEncryptionOptions:
        Enabled: True
      EncryptionAtRestOptions:
        Enabled: True
        KmsKeyId: alias/aws/es
      DomainEndpointOptions:
        EnforceHTTPS: True

  # Lambda function to create OpenSearch Connector for Amazon Bedrock
  CreateOpenSearchBedrockConnectorLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "main.lambda_handler"
      Role: !GetAtt LambdaOpenSearchRole.Arn
      Layers:
        - !Ref CommonLambdaLayer
      Code:
        S3Bucket: !Ref S3BucketCodeArtifact
        S3Key: os_bedrock_connector.zip
      Runtime: python3.12
      Timeout: 600
      Environment:
        Variables:
          AOS_INDEX_NAME: !Ref OpenSearchIndexName
          AOS_HOST: !GetAtt OpenSearchServiceDomain.DomainEndpoint
          AOS_REGION: !Ref AWS::Region
          AOS_SERVICE: "es"
          AOS_USERNAME: !Ref OpenSearchUsername
          AOS_PASSWORD: !Ref OpenSearchPassword
          LAMBDA_ROLE: !GetAtt LambdaOpenSearchRole.Arn
          AOSI_ROLE: !GetAtt IngestionPipelineRole.Arn
          BEDROCK_ROLE: !GetAtt OpenSearchBedrockRole.Arn
          BEDROCK_REGION: !Sub ${BedrockRegion}

  # Amazon OpenSearch Ingestion Pipeline
  IngestionPipeline:
    Type: "AWS::OSIS::Pipeline"
    Properties:
      LogPublishingOptions:
        IsLoggingEnabled: true
        CloudWatchLogDestination:
          LogGroup: !Ref IngestionPipelineLogGroup
      MinUnits: 1
      MaxUnits: 3
      PipelineName: cs5296-ingestion-pipeline
      PipelineConfigurationBody:
        Fn::Sub:
          - "version: '2'\ndynamodb-pipeline:\n  source:\n    dynamodb:\n      acknowledgments: true\n      aws:\n        region: ${REGION}\n        sts_role_arn: ${ROLE_ARN}\n      tables:\n      - table_arn: ${TABLE_ARN}\n        stream:\n          start_position: LATEST\n        export:\n          s3_bucket: ${S3_BUCKET_MAIN}\n          s3_prefix: ddb-to-opensearch-export/\n          s3_region: ${REGION}\n  sink:\n  - opensearch:\n      aws:\n        region: ${REGION}\n        sts_role_arn: ${ROLE_ARN}\n      hosts:\n      - ${DOMAIN_NAME}\n      index: ${INDEX_NAME}\n      index_type: custom\n      document_id: \"${!getMetadata(\\\"primary_key\\\")}\"\n      action: \"${!getMetadata(\\\"opensearch_action\\\")}\"\n      document_version: \"${!getMetadata(\\\"document_version\\\")}\"\n      document_version_type: 'external'"
          - { ROLE_ARN: { "Fn::GetAtt": "IngestionPipelineRole.Arn" }, DOMAIN_NAME: { "Fn::Join": ["", ["https://", { "Fn::GetAtt": OpenSearchServiceDomain.DomainEndpoint }]] }, REGION: { "Ref": "AWS::Region" }, S3_BUCKET_MAIN: { "Ref": "S3BucketMain" }, TABLE_ARN: { "Ref": "ImageStoreDynamodbTableArn" }, INDEX_NAME: { "Ref": "OpenSearchIndexName" } }
