import os

AOS_HOST = os.environ.get('AOS_HOST')
AOS_USERNAME = os.environ.get('AOS_USERNAME')
AOS_PASSWORD = os.environ.get('AOS_PASSWORD')
AOS_INDEX_NAME = os.environ.get("AOS_INDEX_NAME")
DDB_TABLE = os.environ.get("DDB_TABLE")
S3_BUCKET_STANDARD_IA = os.environ.get("S3_BUCKET_STANDARD_IA")
S3_BUCKET_GLACIER_FLEXIBLE_RETRIEVAL = os.environ.get("S3_BUCKET_GLACIER_FLEXIBLE_RETRIEVAL")
S3_BUCKET_GLACIER_INSTANT_RETRIEVAL = os.environ.get("S3_BUCKET_GLACIER_INSTANT_RETRIEVAL")