import os


AOS_HOST = os.environ.get('AOS_HOST')
AOS_USERNAME = os.environ.get('AOS_USERNAME')
AOS_PASSWORD = os.environ.get('AOS_PASSWORD')
AOS_INDEX_NAME = os.environ.get("AOS_INDEX_NAME")
DDB_TABLE = os.environ.get("DDB_TABLE")
S3_BUCKET_MAIN = os.environ.get("S3_BUCKET_MAIN")
S3_BUCKET_STANDARD_IA = os.environ.get("S3_STANDARD_IA_BUCKET")
S3_BUCKET_GLACIER_FLEXIBLE_RETRIEVAL = os.environ.get("S3_GLACIER_FLEXIBLE_RETRIEVAL_BUCKET")
S3_BUCKET_GLACIER_INSTANT_RETRIEVAL = os.environ.get("S3_GLACIER_INSTANT_RETRIEVAL_BUCKET")